bookhouse/urls.py
from django.contrib import admin
from django.urls import path, include

from bookhouse import settings
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('secureLogin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
    #orders
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:book_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:book_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:book_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),

]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='books_by_category'),
    path('category/<slug:category_slug>/<slug:book_slug>/', views.book_detail, name='book_detail'),
    path('search/', views.search, name= 'search'),
    path('submit_review/<int:book_id>',views.submit_review,name='submit_review'),
]

carts/models.py
from django.db import models
from store.models import Book, BookFormat
from accounts.models import Account


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    book_format = models.ManyToManyField(BookFormat, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.book.book_price * self.quantity

    def __unicode__(self):
        return self.book

store/models.py
from django.db import models
from category.models import category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


# Create your models here.

class Book(models.Model):
    book_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    book_description = models.TextField(max_length=500, blank=True)
    book_price = models.IntegerField()
    book_image = models.ImageField(upload_to='photos/products')
    book_stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    book_category = models.ForeignKey(category, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('book_detail', args=[self.book_category.slug, self.slug])

    def __str__(self):
        return self.book_name

    def averageReview(self):
        reviews = ReviewRating.objects.filter(book=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(book=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
            return count


class BookFormatManager(models.Manager):
    def bookformat(self):
        return super(BookFormatManager, self).filter(book_variation='format', is_active=True)


book_variation_choice = (
    ('format', 'format'),
)


class BookFormat(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    book_variation = models.CharField(max_length=100, choices=book_variation_choice)
    book_format_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    creation_date = models.DateTimeField(auto_now=True)

    objects = BookFormatManager()

    def __str__(self):
        return self.book_format_value


class ReviewRating(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class BookGallery(models.Model):
    book = models.ForeignKey(Book, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/books', max_length=255)

    def __str__(self):
        return self.book.book_name

    class Meta:
        verbose_name = 'book gallery'
        verbose_name_plural = 'book gallery'

store/forms.py
from django import forms 
from .models import ReviewRating
class ReviewForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=['subject','review','rating']

carts/views.py
from http.client import HTTPResponse
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Book, BookFormat
from django.core.exceptions import ObjectDoesNotExist

from .models import Cart, CartItem
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, book_id):
    current_user = request.user
    book = Book.objects.get(id=book_id)  # get the book
    #if the user is authenticated
    if current_user.is_authenticated:
        book_formats = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                print(key, value)

                try:
                    book_format = BookFormat.objects.get(book=book, book_variation__iexact=key,
                                                         book_format_value__iexact=value)
                    # list of book formats
                    book_formats.append(book_format)
                except:
                    pass


        is_cart_item_exists = CartItem.objects.filter(book=book, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(book=book, user=current_user)
            # existing book formats -> database
            # current book format -> book_formats
            # item_id -> database
            existing_bookformat_list = []
            id = []
            for item in cart_item:
                existing_bookformat = item.book_format.all()
                existing_bookformat_list.append(list(existing_bookformat))
                id.append(item.id)

            if book_formats in existing_bookformat_list:
                # increase the cart item quantity
                index = existing_bookformat_list.index(book_formats)
                item_id = id[index]
                item = CartItem.objects.get(book=book, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(book=book, quantity=1, user=current_user)
                if len(book_formats) > 0:
                    item.book_format.clear()
                    item.book_format.add(*book_formats)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                book=book,
                quantity=1,
                user=current_user,
            )
            if len(book_formats) > 0:
                cart_item.book_format.clear()
                cart_item.book_format.add(*book_formats)
            cart_item.save()
        return redirect('cart')
    #if the user is not authenticated
    else:
        book_formats = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                print(key, value)

                try:
                    book_format = BookFormat.objects.get(book=book, book_variation__iexact=key,
                                                         book_format_value__iexact=value)
                    # list of book formats
                    book_formats.append(book_format)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # get the cart using cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(book=book, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(book=book, cart=cart)
            # existing book formats -> database
            # current book format -> book_formats
            # item_id -> database
            existing_bookformat_list = []
            id = []
            for item in cart_item:
                existing_bookformat = item.book_format.all()
                existing_bookformat_list.append(list(existing_bookformat))
                id.append(item.id)

            print(existing_bookformat_list)

            if book_formats in existing_bookformat_list:
                # increase the cart item quantity
                index = existing_bookformat_list.index(book_formats)
                item_id = id[index]
                item = CartItem.objects.get(book=book, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(book=book, quantity=1, cart=cart)
                if len(book_formats) > 0:
                    item.book_format.clear()
                    item.book_format.add(*book_formats)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                book=book,
                quantity=1,
                cart=cart,
            )
            if len(book_formats) > 0:
                cart_item.book_format.clear()
                cart_item.book_format.add(*book_formats)
            cart_item.save()
        return redirect('cart')


def remove_cart(request, book_id, cart_item_id):

    book = get_object_or_404(Book, id=book_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(book=book, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(book=book, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, book_id, cart_item_id):
    book = get_object_or_404(Book, id=book_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(book=book, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(book=book, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.book.book_price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.book.book_price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

store/views.py
from http.client import HTTPResponse
from multiprocessing import context
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book, ReviewRating, BookGallery
from category.models import category
from carts.models import CartItem
from django.db.models import Q
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderBook


# Create your views here.

def store(request, category_slug=None):
    book_categories = None
    books = None

    if category_slug is not None:
        book_categories = get_object_or_404(category, slug=category_slug)
        books = Book.objects.filter(book_category=book_categories, is_available=True)
        paginator = Paginator(books, 2)
        page = request.GET.get('page')
        paged_books = paginator.get_page(page)
        books_count = books.count()
    else:
        books = Book.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(books, 6)
        page = request.GET.get('page')
        paged_books = paginator.get_page(page)
        books_count = books.count()

    context = {
        'books': paged_books,
        'books_count': books_count,
    }
    return render(request, 'store/store.html', context)


def book_detail(request, category_slug, book_slug):
    try:
        single_book = Book.objects.get(book_category__slug=category_slug, slug=book_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), book=single_book).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderbook = OrderBook.objects.filter(user=request.user, book_id=single_book.id).exists()
        except OrderBook.DoesNotExist:
            orderbook = None
    else:
        orderbook = None
    # get the reviews
    reviews = ReviewRating.objects.filter(book_id=single_book.id, status=True)

    #get the book gallery
    book_gallery = BookGallery.objects.filter(book_id=single_book.id)

    context = {
        'single_book': single_book,
        'in_cart': in_cart,
        'orderbook': orderbook,
        'reviews': reviews,
        'book_gallery': book_gallery,
    }

    return render(request, 'store/book_detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            books = Book.objects.order_by('-creation_date').filter(
                Q(book_description__icontains=keyword) | Q(book_name__icontains=keyword))
            print(books)
            books_count = books.count()
    context = {
        'books': books,
        'books_count': books_count,
    }
    return render(request, 'store/store.html', context)


def submit_review(request, book_id):
    url = request.META.get('HTTP_REFERER')
    # print(">>>>>>>>>>>>>>>"+ str(book_id)+ "    "+ str(request.user.id))
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, book__id=book_id)
            # print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"+reviews)
            form = ReviewForm(request.POST, instance=reviews)
            res = form.save()
            # print("form result"+res)
            messages.success(request, 'Thank you! Your review has been Updated')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.book_id = book_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been Submitted')
                return redirect(url)

templates/store/book_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <div class="card">
            <!-- <div class="row no-gutters">   -->
            <div class="row g-2 ">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap text-center mainImage">
                            <center><img src="{{ single_book.book_image.url}}" class="img-thumbnail img-fluid"
                                             width=300 height=300></center>
                        </div> <!-- img-big-wrap.// -->

                    </article> <!-- gallery-wrap .end// -->
                    <ul class="thumb">
                        <li>
                            <a href="{{ single_book.book_image.url}}" target="mainImage"><img src="{{ single_book.book_image.url}}" alt="Book Image"></a>
                            {% for i in book_gallery %}
                            <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Book Image"></a>
                            {% endfor %}
                        </li>

                    </ul>
                </aside>
                <main class="col-md-6 border-left">

                    <form action="{% url 'add_cart' single_book.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">

                            <h2 class="title">{{single_book.book_name}}</h2>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if single_book.averageReview < 0.5 %}-o{% elif single_book.averageReview >= 0.5 and single_book.averageReview < 1  %}-half-o{% endif %}" aria-hidden="true"></i> 
                                    <i class="fa fa-star{% if single_book.averageReview < 1.5 %}-o{% elif single_book.averageReview >= 1.5 and single_book.averageReview < 2  %}-half-o{% endif %}" aria-hidden="true"></i> 
                                    <i class="fa fa-star{% if single_book.averageReview < 2.5 %}-o{% elif single_book.averageReview >= 2.5 and single_book.averageReview < 3  %}-half-o{% endif %}" aria-hidden="true"></i> 
                                    <i class="fa fa-star{% if single_book.averageReview < 3.5 %}-o{% elif single_book.averageReview >= 3.5 and single_book.averageReview < 4  %}-half-o{% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if single_book.averageReview < 4.5 %}-o{% elif single_book.averageReview >= 4.5 and single_book.averageReview < 5  %}-half-o{% endif %}" aria-hidden="true"></i>
                                    <span> {{single_book.countReview}} reviews</span>
                                </span>

        
                            </div>
                            

                            <div class="mb-3">
                                <var class="price h4"> ${{single_book.book_price}}</var>
                            </div>

                            <p>{{single_book.book_description}}</p>

                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Format</h6>
                                    <select name="format" class="form-control" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in single_book.bookformat_set.bookformat %}
                                        <option value="{{i.book_format_value|lower }}">{{i.book_format_value|capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <hr>
                            {% if single_book.book_stock <= 0 %}
                            <h5 class="text-danger">Out of Stock</h5>
                            {% else %}
                            <button type="submit" class="btn  btn-primary"><span class="text">Add to cart</span>
                                <i class="fas fa-shopping-cart"></i></button>
                            {% endif %}
                        </article> <!-- product-info-aside .// -->
                    </form>
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

        <br>

        <div class="row">
            <div class="col-md-9">


              
                <form action="{% url 'submit_review' single_book.id %}" method="POST" >
                    {% csrf_token %}
                    <h5> Write Your Review</h5>
                    
                    <div>
                        <!--Rating star-->
                        <label>How do you rate this product?</label>
                        <br>
                        <div class="rate">
                            <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
                            <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                            <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
                            <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                            <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
                            <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                            <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
                            <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                            <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
                            <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
                        </div>
                        <br>
                        Review Title: 
                    <input type="text" class="form-control" name="subject" >
                    <br>
                    Review: 
                    <textarea name="review" rows="4" class="form-control"></textarea>
                    <br>
                    {% if user.is_authenticated %}
                    {% if orderbook %}

                    <input type="submit" value="submit Review" class="btn btn-primary" >
                    {% else %}
                    <p>You must purchase this book to post a review</p>
                    {% endif %}
                    {% else %}
                    <p>You must be logged in to post a review <span><a href="{% url 'login' %}">Login now</a></span></p>
                        
                    {% endif%}
                    </div>
                    {% include 'includes/alerts.html' %}

                </form>
                <br>
                <header class="section-heading">
                    <h3>Customer Reviews </h3>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if single_book.averageReview < 0.5 %}-o {% elif single_book.averageReview >= 0.5 and single_book.averageReview < 1  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_book.averageReview < 1.5 %}-o {% elif single_book.averageReview >= 1.5 and single_book.averageReview < 2  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_book.averageReview < 2.5 %}-o {% elif single_book.averageReview >= 2.5 and single_book.averageReview < 3  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_book.averageReview < 3.5 %}-o {% elif single_book.averageReview >= 3.5 and single_book.averageReview < 4  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_book.averageReview < 4.5 %}-o {% elif single_book.averageReview >= 4.5 and single_book.averageReview < 5  %}-half-o {% endif %}" aria-hidden="true"></i>
                            <span> {{single_book.countReview}} reviews</span>
                        </span>

                    </div>

                </header>
                {% for review in reviews %}
                <article class="box mb-3 container ml-2 ">
                    <div class="icontext w-100">
                        
                        <div class="text">
                            <br>
                            <span class="date text-muted float-md-right">{{review.updated_at}}</span>
                            <h6 class="mb-1">{{review.user.full_name }}</h6>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if review.rating == 0.5 %}-half-o {% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 1.5 %}-half-o {% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 2.5 %}-half-o {% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 3.5 %}-half-o {% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if review.rating == 4.5 %}-half-o {% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                                </span>

                            </div>

                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <h6> {{review.subject}}</h6>
                        <p>
                            {{review.review}}
                        </p>
                    </div>
                </article>
                {% endfor %}


            </div> <!-- col.// -->
        </div> <!-- row.// -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}